# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer0.luther.systems:
  peer0.org1.luther.systems:
  peer1.org1.luther.systems:
  ca.org1.luther.systems:

networks:
  byfn:

services:
  ca.org1.luther.systems:
    image: $IMAGE_NS/fabric-ca:$CA_IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.luther.systems-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.luther.systems-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.luther.systems/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  orderer0.luther.systems:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.luther.systems
    container_name: orderer0.luther.systems
    environment:
      - FABRIC_LOGGING_SPEC
    networks:
      - byfn

  peer0.org1.luther.systems:
    container_name: peer0.org1.luther.systems
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.luther.systems
    environment:
      - FABRIC_LOGGING_SPEC
    networks:
      - byfn

  peer1.org1.luther.systems:
    container_name: peer1.org1.luther.systems
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.luther.systems
    environment:
      - FABRIC_LOGGING_SPEC
    networks:
      - byfn
